### ISSUE TITLE
Conflict with Modernizr

### ISSUE THREAD

**Issue by chrisblakley** [ridjohansen/css_browser_selector#14]
When called, it seems that Modernizr classes are being replaced with CSSBS classes.

**Comment by marcorieser** [comment]
I fixed this for me, look at [my pull-request](https://github.com/ridjohansen/css_browser_selector/pull/11)

**Comment by ihorzenich** [comment]
+1 please fix.

**Comment by ihorzenich** [comment]
Fixed in v0.8
